# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('1', 'Chauchau'), ('2', 'SomethingElse')], max_length=3)),
                ('area', models.CharField(choices=[('KTM', 'Kathmandu'), ('BRT', 'Biratnagar'), ('DHK', 'Dhulikhel')], max_length=3)),
                ('price', models.CharField(max_length=3)),
                ('date', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
