# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_prices',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='raw_prices',
            name='price',
            field=models.IntegerField(),
        ),
    ]
