# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160611_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('1', 'Chauchau'), ('2', 'SomethingElse')], max_length=3)),
                ('area', models.CharField(choices=[('KTM', 'Kathmandu'), ('BRT', 'Biratnagar'), ('DHK', 'Dhulikhel')], max_length=3)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
