# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='area',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Dhulikhel', 'Dhulikhel'), ('Jhapa', 'Jhapa')], max_length=3),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.CharField(choices=[('Chauchau', 'Chauchau'), ('SomethingElse', 'SomethingElse'), ('SubashLeJptBolyo', 'SubashLeJPtBolyo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='raw_prices',
            name='area',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Dhulikhel', 'Dhulikhel'), ('Jhapa', 'Jhapa')], max_length=3),
        ),
        migrations.AlterField(
            model_name='raw_prices',
            name='product',
            field=models.CharField(choices=[('Chauchau', 'Chauchau'), ('SomethingElse', 'SomethingElse'), ('SubashLeJptBolyo', 'SubashLeJPtBolyo')], max_length=3),
        ),
    ]
