# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160731_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='area',
            field=models.CharField(choices=[(1, 'Dairy'), (2, 'Digestives'), (3, 'Drinks and Beverages'), (4, 'Food'), (5, 'Morning Misc'), (7, 'NUtrition'), (8, 'Snackes')], max_length=20),
        ),
    ]
