# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160731_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='area',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Dhulikhel', 'Dhulikhel')], max_length=20),
        ),
    ]
